### PR TITLE
View best sellers

### PR DESCRIPTION
**Pull request by MinaNemr**
#101

@omarkamal95 please review documentation
@Veegas please review code

### CODE REVIEW

**Comment by omarkamal95** [comment]
@MinaNemr Doc reviewed . Tamam ya wa7sh.

**Comment by MinaNemr** [comment]
@Mernawaseif please review UMLs
@Israa-Elwan please review scenario

**Comment by Mernawaseif** [comment]
@MinaNemr UMLs reviewed, tmam

**Comment by Israa-Elwan** [comment]
@MinaNemr user can click on best sellers and be directed to the right page but empty one he can't view best sellers

**Pull request merged**
