### PR TITLE
Add a book to to be read list

### PR DESCRIPTION
**Pull request by MinaNemr**

### CODE REVIEW

**Comment by MinaNemr** [comment]
#77 
@omarkamal95 please review documentation
@Veegas please review code

**Comment by MinaNemr** [comment]
@Mernawaseif please review UML diagrams
@Israa-Elwan please review scenatrio

**Comment by Mernawaseif** [comment]
@MinaNemr done with reviewing UMLs, no comments on them.

**Comment by omarkamal95** [comment]
@MinaNemr  documentation reviewed. all good.

**Comment by Israa-Elwan** [comment]
@MinaNemr nothing wrong with the story scenarios

**Comment by Veegas** [comment]
@MinaNemr  Code tamam

**Comment by MinaNemr** [comment]
#77

**Pull request merged**
